export const ADD_A_CATEGORY = 'ADD_A_CATEGORY';
export const REMOVE_A_CATEGORY = 'REMOVE_A_CATEGORY';
export const REMOVE_ALL_CATEGORIES = 'REMOVE_ALL_CATEGORIES';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENT_ITEM = 'INCREMENT_ITEM';
export const DECREMENT_ITEM = 'DECREMENT_ITEM';
export const DELETE_ALL = 'DELETE_ALL';
